using Advent22.Lib.Day1;
using Advent22.Lib.Day2;
using Advent22.Lib.Day3;
using Advent22.Lib.Day4;
using Advent22.Lib.Day5;
using Advent22.Lib.Day6;

Console.WriteLine($"Day 1 Task 1 Answer: {Day1.Part1Solution()}");
Console.WriteLine($"Day 1 Task 2 Answer: {Day1.Part2Solution()}");
Console.WriteLine();
Console.WriteLine($"Day 2 Task 1 Answer: {Day2.Part1Solution()}");
Console.WriteLine($"Day 2 Task 2 Answer: {Day2.Part2Solution()}");
Console.WriteLine();
Console.WriteLine($"Day 3 Task 1 Answer: {Day3.Part1Solution()}");
Console.WriteLine($"Day 3 Task 2 Answer: {Day3.Part2Solution()}");
Console.WriteLine();
Console.WriteLine($"Day 4 Task 1 Answer: {Day4.Part1Solution()}");
Console.WriteLine($"Day 4 Task 2 Answer: {Day4.Part2Solution()}");
Console.WriteLine();
Console.WriteLine($"Day 5 Task 1 Answer: {Day5.Part1Solution()}");
Console.WriteLine($"Day 5 Task 2 Answer: {Day5.Part2Solution()}");
Console.WriteLine();
Console.WriteLine($"Day 6 Task 1 Answer: {Day6.Part1Solution()}");
Console.WriteLine($"Day 5 Task 2 Answer: {Day6.Part2Solution()}");